config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users

  resources :bowling_games do
    member do
      get "bowling_frame"
      get "calculate_score"
    end
    collection do
      post "score_collecter"
    end
  end
end

app/models/bowling_game.rb
class BowlingGame < ActiveRecord::Base
  PINS = 10

  #Calculate total score
  def calc_score(frame_scores)
    total = []
    frame_scores.each_with_index do |frame_score, index|

    	puts frame_scores.inspect
      if strike?(frame_score)
        total << frame_scores[index..index+2].flatten.compact[0..2].sum
      elsif spare?(frame_score)
        puts frame_scores[index..index+1].flatten.compact[0..2].inspect
        total << frame_scores[index..index+1].flatten.compact[0..2].sum if frame_scores[index..index+1].flatten.compact[0..2].length >=3
      else
        total << frame_score.sum
      end
    end
    return total.sum
  end

  #Check for spares
  def spare?(frame_score)
    frame_score.sum == PINS
  end

  #Check for strikes
  def strike?(frame_score)
    (frame_score[0] || frame_score[1]) == PINS
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bowling_games_controller.rb
class BowlingGamesController < ApplicationController
  before_action :authenticate_user!

  TOTAL_FRAMES = 10
  before_action :set_bowling_game, only: [:show, :edit, :update, :destroy,:bowling_frame,:score_collecter,:calculate_score]

  # GET /bowling_games
  # GET /bowling_games.json
  def index
    @bowling_games = BowlingGame.all
  end

  # GET /bowling_games/1
  # GET /bowling_games/1.json
  def show
  end

  # GET /bowling_games/new
  def new
    @bowling_game = BowlingGame.new
  end

  # GET /bowling_games/1/edit
  def edit
  end

  # POST /bowling_games
  # POST /bowling_games.json
  def create
    @bowling_game = BowlingGame.new(bowling_game_params)

    respond_to do |format|
      if @bowling_game.save
        format.html { redirect_to @bowling_game, notice: 'Bowling game was successfully created.' }
        format.json { render :show, status: :created, location: @bowling_game }
      else
        format.html { render :new }
        format.json { render json: @bowling_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bowling_games/1
  # PATCH/PUT /bowling_games/1.json
  def update
    respond_to do |format|
      if @bowling_game.update(bowling_game_params)
        format.html { redirect_to @bowling_game, notice: 'Bowling game was successfully updated.' }
        format.json { render :show, status: :ok, location: @bowling_game }
      else
        format.html { render :edit }
        format.json { render json: @bowling_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bowling_games/1
  # DELETE /bowling_games/1.json
  def destroy
    @bowling_game.destroy
    respond_to do |format|
      format.html { redirect_to bowling_games_url, notice: 'Bowling game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #building frame logic
  def bowling_frame
    if params[:frame_number].blank?
      session["game_#{params[:id]}".to_sym] = Array.new
      @frame_number = 1
    else
      @frame_number = params[:frame_number].to_i+1
    end
  end

  #collecting the score for each frames and store it on the session with dynamic key
  def score_collecter
    scores = [params[:try_one].to_i,params[:try_two].to_i]
    if scores.include?(10)
      scores = [10]
    end
    frame_number = params[:frame_number].to_i
    session["game_#{params[:id]}".to_sym] << scores
    unless frame_number == TOTAL_FRAMES
      redirect_to bowling_frame_bowling_game_path(@bowling_game,frame_number: frame_number)
    else
      redirect_to calculate_score_bowling_game_path(@bowling_game,frame_number: frame_number)
    end
  end

  #calculating score and generte the final result
  def calculate_score
    frame_scores = session["game_#{params[:id]}".to_sym]
    if frame_scores.length >= TOTAL_FRAMES
      @total_score = @bowling_game.calc_score(frame_scores)
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bowling_game
    @bowling_game = BowlingGame.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bowling_game_params
    params.require(:bowling_game).permit(:player_name, :player_email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bowling_games_helper.rb
module BowlingGamesHelper
end

app/views/bowling_games/_form.html.erb
<%= form_for(@bowling_game) do |f| %>
  <% if @bowling_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bowling_game.errors.count, "error") %> prohibited this bowling_game from being saved:</h2>

      <ul>
      <% @bowling_game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_name %><br>
    <%= f.text_field :player_name %>
  </div>
  <div class="field">
    <%= f.label :player_email %><br>
    <%= f.text_field :player_email %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bowling_games/bowling_frame.html.erb
FRAME # <%=@frame_number%>

<%=form_tag (score_collecter_bowling_games_path)%>
<%= hidden_field_tag :frame_number, @frame_number%>
<%= hidden_field_tag :id, @bowling_game.id%>
<%= text_field_tag :try_one%>
<%= text_field_tag :try_two%>
<%=submit_tag "Next"%>

app/views/bowling_games/calculate_score.html.erb
<h1>Congragulations Your Total Score is: <%=@total_score%> </h1>

Frame Score: <%=session["game_#{@bowling_game.id}".to_sym]%>

app/views/bowling_games/edit.html.erb
<h1>Editing Bowling Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @bowling_game %> |
<%= link_to 'Back', bowling_games_path %>

app/views/bowling_games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bowling Games</h1>

<table>
  <thead>
    <tr>
      <th>Player name</th>
      <th>Player email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bowling_games.each do |bowling_game| %>
      <tr>
        <td><%= bowling_game.player_name %></td>
        <td><%= bowling_game.player_email %></td>
        <td><%= link_to 'Show', bowling_game %></td>
        <td><%= link_to 'Edit', edit_bowling_game_path(bowling_game) %></td>
        <td><%= link_to 'Start The Game', bowling_frame_bowling_game_path(bowling_game) %></td>
        <td> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bowling game', new_bowling_game_path %>

app/views/bowling_games/new.html.erb
<h1>New Bowling Game</h1>

<%= render 'form' %>

<%= link_to 'Back', bowling_games_path %>

app/views/bowling_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player name:</strong>
  <%= @bowling_game.player_name %>
</p>

<p>
  <strong>Player email:</strong>
  <%= @bowling_game.player_email %>
</p>

<p>
  <strong>Frame scores:</strong>
  <%= @bowling_game.frame_scores %>
</p>

<p>
  <strong>Total score:</strong>
  <%= @bowling_game.total_score %>
</p>

<%= link_to 'Edit', edit_bowling_game_path(@bowling_game) %> |
<%= link_to 'Back', bowling_games_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
   <li><%= link_to 'Bowling', bowling_games_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bowling Game" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bowling Game" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>